config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  
  namespace :api do
    resources :answers, as: 'api_answer'
    resources :evaluables, as: 'api_evaluable'
    resources :journeys, as: 'api_journey'
    resources :lessons, as: 'api_lesson'
    resources :questions, as: 'api_question'
    resources :quizzes, as: 'api_quiz'
    resources :subjects, as: 'api_subject'
    resources :stats, as: 'api_stats'
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    mailer: 'users/mailer',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  get '/challenges', to: 'home#challenges', as: 'challenges'
  get '/classroom', to: 'home#classroom', as: 'classroom'
  get '/about', to: 'about#index', as: 'about'
  get '/data/questions', to: 'home#question', as: 'question'
  get '/data/subjects', to: 'home#subject', as: 'subject'
  get '/data', to: 'home#statistics', as: 'statistics'
  get '/data/settings', to: 'home#configurations', as: 'configurations'

  get '/quiz(/:subject/:level/:journey)', to: 'quiz#index', as: 'quiz'
  get '/results/:id', to: 'quiz#results', as: 'results'
  get '/lesson/:id', to: 'lesson#index', as: 'lesson'

  post '/quiz', to: 'quiz#submit'

  # Defines the root path route ('/')
  # root 'articles#index'
end

app/models/evaluable.rb
class Evaluable < ApplicationRecord
  belongs_to :stat, class_name: 'Stat', foreign_key: 'stat_id'
  belongs_to :subject
end

app/controllers/api/evaluables_controller.rb
class Api::EvaluablesController < ApplicationController
  before_action :set_evaluable, only: %i[ show edit update destroy ]

  # GET /evaluables or /evaluables.json
  def index
    @evaluables = Evaluable.all
  end

  # GET /evaluables/1 or /evaluables/1.json
  def show
  end

  # GET /evaluables/new
  def new
    @evaluable = Evaluable.new
  end

  # GET /evaluables/1/edit
  def edit
  end

  # POST /evaluables or /evaluables.json
  def create
    @evaluable = Evaluable.new(evaluable_params)

    respond_to do |format|
      if @evaluable.save
        format.html { redirect_to evaluable_url(@evaluable), notice: "Evaluable was successfully created." }
        format.json { render :show, status: :created, location: @evaluable }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @evaluable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluables/1 or /evaluables/1.json
  def update
    new_tags = if evaluable_params['tag']
                 if evaluable_params['tag'] == ','
                   []
                 elsif @evaluable.tags.include?(evaluable_params['tag'])
                  @evaluable.tags - [evaluable_params['tag']]
                 else
                   @evaluable.tags + [evaluable_params['tag']]
                 end
               else
                 @evaluable.tags
               end

    new_focus = if evaluable_params['focus']
                  if evaluable_params['focus'].to_i == @evaluable.focus
                    0
                  else
                    evaluable_params['focus'].to_i
                  end
                else
                  @evaluable.focus
                end

    @evaluable.update(tags: new_tags, focus: new_focus)
    render json: @evaluable
  end

  # DELETE /evaluables/1 or /evaluables/1.json
  def destroy
    @evaluable.destroy

    respond_to do |format|
      format.html { redirect_to evaluables_url, notice: "Evaluable was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_evaluable
    @evaluable = Evaluable.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def evaluable_params
    params.fetch(:evaluable, {}).permit(:tag, :focus)
  end
end

app/helpers/evaluables_helper.rb
module EvaluablesHelper
end

app/views/evaluables/_evaluable.html.erb
<div id="<%= dom_id evaluable %>">
</div>

app/views/evaluables/_form.html.erb
<%= form_with(model: evaluable) do |form| %>
  <% if evaluable.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(evaluable.errors.count, "error") %> prohibited this evaluable from being saved:</h2>

      <ul>
        <% evaluable.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/evaluables/edit.html.erb
<h1>Editing evaluable</h1>

<%= render "form", evaluable: @evaluable %>

<br>

<div>
  <%= link_to "Show this evaluable", @evaluable %> |
  <%= link_to "Back to evaluables", evaluables_path %>
</div>

app/views/evaluables/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Evaluables</h1>

<div id="evaluables">
  <% @evaluables.each do |evaluable| %>
    <%= render evaluable %>
    <p>
      <%= link_to "Show this evaluable", evaluable %>
    </p>
  <% end %>
</div>

<%= link_to "New evaluable", new_evaluable_path %>

app/views/evaluables/new.html.erb
<h1>New evaluable</h1>

<%= render "form", evaluable: @evaluable %>

<br>

<div>
  <%= link_to "Back to evaluables", evaluables_path %>
</div>

app/views/evaluables/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @evaluable %>

<div>
  <%= link_to "Edit this evaluable", edit_evaluable_path(@evaluable) %> |
  <%= link_to "Back to evaluables", evaluables_path %>

  <%= button_to "Destroy this evaluable", @evaluable, method: :delete %>
</div>