config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  
  namespace :api do
    resources :answers, as: 'api_answer'
    resources :evaluables, as: 'api_evaluable'
    resources :journeys, as: 'api_journey'
    resources :lessons, as: 'api_lesson'
    resources :questions, as: 'api_question'
    resources :quizzes, as: 'api_quiz'
    resources :subjects, as: 'api_subject'
    resources :stats, as: 'api_stats'
  end

  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    mailer: 'users/mailer',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks'
  }

  get '/challenges', to: 'home#challenges', as: 'challenges'
  get '/classroom', to: 'home#classroom', as: 'classroom'
  get '/about', to: 'about#index', as: 'about'
  get '/data/questions', to: 'home#question', as: 'question'
  get '/data/subjects', to: 'home#subject', as: 'subject'
  get '/data', to: 'home#statistics', as: 'statistics'
  get '/data/settings', to: 'home#configurations', as: 'configurations'

  get '/quiz(/:subject/:level/:journey)', to: 'quiz#index', as: 'quiz'
  get '/results/:id', to: 'quiz#results', as: 'results'
  get '/lesson/:id', to: 'lesson#index', as: 'lesson'

  post '/quiz', to: 'quiz#submit'

  # Defines the root path route ('/')
  # root 'articles#index'
end

app/views/shared/_footer.html.erb
</div><footer class="text-bg-primary w-100 p-2" style="z-index: 1; position: relative;">&copy; 2021-2023 Standardized Experience<br>
<span class="text-dark fs-7"><i>Standardized Experience 4.4.1 "Plurality"<br>Logo by <i class="bi-discord"></i> karu#0170</i></span></footer>

app/views/shared/_header.html.erb
<nav class='navbar navbar-expand navbar-dark bg-primary py-1 px-2' style="z-index: 1"><ul class='navbar-nav'>
    <%=link_to root_path, class: "py-0 my-0 nav-link #{current_page?(root_path) ? 'active' : ''}" do %>
        <li class='nav-item'>
          <%= fa_icon("home") %>
          <span class='align-middle erasable'>Home</span>
        </li>
    <% end %>

    <%=link_to question_path, class: "py-0 my-0 nav-link #{current_page?(question_path) || current_page?(subject_path) ? 'active' : ''}" do %>
        <li class='nav-item'>
          <%= fa_icon("folder") %>
          <span class='align-middle erasable'>Data</span>
        </li>
    <% end %>

    <%=link_to quiz_path, class: "py-0 my-0 nav-link #{current_page?(quiz_path) ? 'active' : ''}" do %>
        <li class='nav-item'>
          <%= fa_icon("file") %>
          <span class='align-middle erasable'>Practice</span>
        </li>
    <% end %>

    <%=link_to about_path, class: "py-0 my-0 nav-link #{current_page?(about_path) ? 'active' : ''}" do %>
        <li class='nav-item'>
          <%= fa_icon("info") %>
          <span class='align-middle erasable'>About</span>
        </li>
    <% end %>

</ul>
  <% if current_user %>
    <div class='text-white nav-item navbar-text ms-auto me-0 bold pe-2'>
      <%= current_user.username %>
      <%= link_to destroy_user_session_path, method: :delete  do %>
        <%= fa_icon 'sign-out-alt', type: 'solid', class: 'align-middle'%>
      <% end %>
    </div>
  <% end %>
  </nav>
  <div id='page' class="bg-light p-3">
    <%= image_tag('logo', { id: 'standardized-image', draggable: false }) %>

app/views/shared/_nav.html.erb
<div class="btn-group d-flex" role="group" aria-label="Basic example">
  <% buttons.each do |data_button| %>
    <%= link_to (current_page?(data_button[0]) ? '#' : data_button[0]), class: "btn btn-primary p-1 #{current_page?(data_button[0]) ? 'active w-100 text-info' : 'text-white'}" do %>
    <%= fa_icon data_button[2] %><br><%= data_button[1] %>
    <% end %>
  <% end %>
</div>

app/views/shared/_notification.html.erb
<div class="notice"><%= notice %></div>
<% unless alert == nil %>
  <div class="alert alert-danger alert-dismissible" role="alert"><%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>